---

R1:
  hostname: 10.0.12.1
  groups:
    - cisco_group

R2:
  hostname: 10.0.12.2
  groups:
    - cisco_group

R3:
  hostname: 10.0.34.3
  groups:
    - cisco_group

R4:
  hostname: 10.0.34.4
  groups:
    - cisco_group

#R5:
#  hostname: 10.0.56.5
#  groups:
#    - cisco_group
#
#R6:
#  hostname: 10.0.56.5
#  groups:
#    - cisco_group

R7:
  hostname: 10.0.27.7
  groups:
    - cisco_group

R8:
  hostname: 10.0.18.8
  groups:
    - cisco_group